name: Build and Push Docker Image
on:
  push:
    branches:
      - '**'
    tags:
      - '**'

env:
  HARBOR_URL: harbor.supaperman.net
  PROJECT_NAME: library
  IMAGE_NAME: dht22-go

jobs:
  build:
    if: github.event_name == 'push' && !contains(github.ref, 'refs/pull/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ env.HARBOR_URL }}
          username: ${{ secrets.HARBOR_ROBOT_USERNAME }}
          password: ${{ secrets.HARBOR_ROBOT_PASSWORD }}

      - name: Create TAG
        run: |
          TAG=$(echo $GITHUB_REF | sed 's|refs/heads/||' | sed 's|refs/tags/||' )
          echo "DOCKER_TAG=$TAG" >> $GITHUB_ENV

      - name: Build the Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.HARBOR_URL }}/${{ env.PROJECT_NAME }}/${{ env.IMAGE_NAME }}:${{ DOCKER_TAG }}
          platforms: linux/arm64
